### ISSUE TITLE
GPL?

### ISSUE THREAD

**Issue by alexanderkjeldaas** [PLSysSec/lio#44]
I see that this is labeled as GPL on hackage.  I'm guessing that it won't be included in a few web frameworks that are BSD3-licensed because of this (say servant).

OTOH, I can't find a LICENSE file, so maybe this haven't been given much thought?

**Comment by deian** [comment]
oh good catch. we decided on MIT a while back; I should fix this.

**Comment by deian** [comment]
done: https://github.com/PLSysSec/lio/commit/a16ef668ba4162dd8f891707b461719c69497f31
